import type { Metadata } from "next";
import "./globals.css";
import { UserProvider, useUser } from "@auth0/nextjs-auth0/client";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { getSession } from "@auth0/nextjs-auth0";
import LoggedInUserWidget from "@/components/user";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();
    return (
        <html lang="en">
            <UserProvider user={session?.user}>
                <body className={cn("dark min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
                    <div className="flex justify-end p-4">
                        <LoggedInUserWidget />
                    </div>
                    {children}
                </body>
            </UserProvider>
        </html>
    );
}
